routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'is_admin','prefix'=>'admin','namespace'=>'Admin\Users'],function () {
  Route::get('/','UserController@index')->name('admin.index');
  Route::get('/users','UserController@users')->name('admin.users');
  Route::get('/users/create','UserController@create')->name('user.register');
  Route::post('/users/store','UserController@store')->name('user.store');
  Route::put('/users/{id}','UserController@update')->name('user.update');
  Route::get('/users/{id}','UserController@edit')->name('user.edit');
  Route::post('/users/upload','UserController@upload')->name('user.upload');
  Route::get('/users/download/1','UserController@download')->name('user.download');
  Route::delete('/delete/{id}','UserController@destroy')->name('admin.destroy');
});

Route::group(['prefix'=>'category', 'as' => 'category.','namespace'=>'Admin\Categories'],function () {
    Route::resource('','CategoryController',['parameters' => [
        '' => 'id',
    ]]);


});
Route::group(['prefix'=>'news', 'as' => 'news.','namespace'=>'Admin\News'],function () {
    Route::resource('','NewsController',['parameters' => [
        '' => 'id',
    ]]);
    Route::post('{id}/addImage','NewsController@upload')->name('addImage');

});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class News extends Model
{
    protected $fillable= ['title','description','image','categories'];
    public function categories()
    {
        return $this->belongsToMany(Category::class,'categories_news');
    }
    public function images()
    {
        return $this->hasMany(Image::class);
    }

}

app/Http/Controllers/Admin/News/NewsController.php
<?php

namespace App\Http\Controllers\Admin\News;

use App\Contracts\CategoryInterface;
use App\Contracts\NewsInterface;
use App\Http\Requests\ImgUpload;
use App\Http\Requests\NewsCreate;
use App\Models\News;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected  $newsRepo;
    protected  $categoryRepo;

    public function __construct(NewsInterface $news,CategoryInterface $category)
    {
        $this->newsRepo = $news;
        $this->categoryRepo = $category;
    }

    public function index()
    {
       $news =  $this->newsRepo->all();
        return view('admin.news.index',compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   $categories = $this->categoryRepo->all();
        return view('admin.news.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NewsCreate $request)
    {
      $this->newsRepo->store($request);
      return redirect()->route('news.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = $this->newsRepo->edit($id);
        $categories = $this->categoryRepo->all();
        return view('admin.news.edit',compact(['news','categories']));
    }

  public function upload($id,ImgUpload $request)
    {
      $this->newsRepo->getImages($id,$request);

      return redirect()->route('news.edit',$id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NewsCreate $request, $id)
    {
         $this->newsRepo->update($id, $request);
         return redirect()->route('news.index',$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->newsRepo->deleteNews($id);
        return response()->json(['id'=>$id]);
    }
}

resources/views/admin/news/create.blade.php
@extends('layouts.app')
@section('graph')
@endsection
{{--@section('notifications')
@endsection--}}
@section('content')
    <div class=" row justify-content-center">
        <div class="col-md-8">
            <div class="card  mt-4">
                <div class ='card-header  '> Add news</div>
                <div class="card-body ">
                    <form method="POST" action="{{ route('news.store') }}" class="container" enctype="multipart/form-data">
                        @csrf
                        <div class=" ">
                            <div class="text-dark ">
                                <div class="form-group row">
                                    <label for="name" class="col-md-2 col-form-label ">{{ __('Name') }}</label>
                                    <div class="col-md-8">
                                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="title" required autofocus>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="description" class="col-md-2 col-form-label pr-0 ">Description</label>
                                    <div class="col-md-8">
                                        <textarea  id='description' class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="description"  required >  </textarea>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="select_categ" class="col-md-2 col-form-label ">Category</label>
                                    <div class="col-md-8 ">
                                        <select name="categories[]" id="select_categ" class="form-control" multiple="multiple">
                                            @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-2">  Upload</div>
                                    <div class="input-group mb-3 col-md-8">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="inputGroupFile02" name="image[]" multiple="multiple">
                                            <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">Choose file</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row mb-0">
                                    <div class="col-md-3 offset-md-9">
                                        <button type="submit" class="btn btn-primary ">
                                            Create
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                @if($errors->any())

                <div class="card-footer">
                    <div class="alert alert-danger">{{$errors->first()}}</div>
                </div>
                    @endif
            </div>
        </div>
    </div>

@endsection

resources/views/admin/news/edit.blade.php
@extends('layouts.app')
@section('graph')
@endsection
{{--@section('notifications')
@endsection--}}
@section('content')
    <div class="container_fluid">
        <div class=" row justify-content-center">
            <div class="col-md-8">
                <div class="card  mt-4">
                    <div class ='card-header  '> Edit news</div>
                    <div class="card-body ">
                        <form method="POST" action="{{ route('news.update', $news->id) }}" class="container" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class=" ">
                                <div class="text-dark ">
                                    <div class="form-group row">
                                        <label for="name" class="col-md-2 col-form-label ">{{ __('Name') }}</label>
                                        <div class="col-md-8">
                                            <input id="name" type="text"  value='{{$news->title}}' class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="title" required autofocus>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="description" class="col-md-2 col-form-label pr-0 ">Description</label>
                                        <div class="col-md-8">
                                            <textarea  id='description' class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="description"  required >{{$news->description}}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="select_categ" class="col-md-2 col-form-label ">Category</label>
                                        <div class="col-md-8 ">
                                            <select name="categories[]" id="select_categ" class="form-control" multiple="multiple">
                                                @foreach($categories as $category)

                                                    <option value="{{$category->id}}" {{$category->news()->find($news->id) ? 'selected' : ''       }}>{{$category->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-3 offset-md-9">
                                            <button type="submit" class="btn btn-primary ">
                                                Change
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    @if($errors->any())
                        <div class="card-footer">
                            <div class="alert alert-danger">{{$errors->first()}}</div>
                        </div>
                    @endif
                </div>
            </div>
        </div>

        <div class="row justify-content-center mt-5">

            <form action="{{route('news.addImage',$news->id)}}" enctype="multipart/form-data" method="POST" class="upload_form" {{--data-id="{{$news->id}}"--}}>
                @csrf
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" id="files" class="custom-file-input" name="image[]" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" multiple="multiple">
                        <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                    </div>
                    <div class="input-group-append">
                        <button class="btn btn-outline-primary" type="submit" id="inputGroupFileAddon04" >upload</button>
                    </div>

                </div>
                <output id ='result'></output>
            </form>

        </div>

        <div class="row">
            <!-- Page Content -->
            <div class="container">

                <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">News galery</h1>

                <hr class="mt-2 mb-5">

                <div class="row text-center text-lg-left">
        @foreach($news->images as $item)
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="{{$item->getImgPath()}}" alt="">
                        </a>
                    </div>
                    @endforeach
                   {{-- <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/aob0ukAYfuI/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/EUfxH-pze7s/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/M185_qYH8vg/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/sesveuG_rNo/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/AvhMzHwiE_0/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/2gYsZUmockw/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/EMSDtjVHdQ8/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/8mUEy0ABdNE/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/G9Rfc1qccH4/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/aJeH0KcFkuc/400x300" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-6">
                        <a href="#" class="d-block mb-4 h-100">
                            <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/p2TQ-3Bh3Oo/400x300" alt="">
                        </a>
                    </div>--}}
                </div>

            </div>
            <!-- /.container -->
        </div>
    </div>
@endsection

resources/views/admin/news/index.blade.php
@extends('layouts.app')
@section('graph')
@endsection
@section('style')
    <style>
        .sized_img {
            max-width: 100px !important;
        }
    </style>
@endsection
@section('datatable')
    {{--<img src="{{App\Models\News::find(94)->getImgPath('images/6k0L30ZymKmPpbp81tlMR7Yi8sEX3SFairT9RGxq.png')}}" alt="">--}}

    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header clearfix">
            <i class="fas fa-table"></i>
            Data Table Example
            <a href="{{route('news.create')}}" class="btn btn-info float-right">create </a>

        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>
                    </tfoot>
                    <tbody>

                    {{--{{dd($news->find(94)->images()->first()->getImgPath(1))}}--}}

                    @foreach($news  as $item)
                        <tr id="{{$item->id}}" class="text-center">
                            <td><a href="{{route('news.edit',['id'=>$item->id])}}">{{$item->title}}</a></td>
                            <td>{{$item->description}}</td>
                            <td><img src="{{$item->images()->first() ? $item->images->first()->getImgPath() : ''}}"
                                     alt="" class="img-fluid sized_img"></td>
                            <td class="text-center">
                                <a href="{{route('news.destroy',$item->id)}}"
                                   data-toggle="modal" data-target="#deleteModal" class='closs-item'
                                   data-id="{{$item->id}}" data-method='delete'><i
                                            class="fas fa-times"></i> </a>
                            </td>
                        </tr>
                    @endforeach
                    {{$news->links('vendor.pagination.bootstrap-4')}}


                    </tbody>

                </table>
            </div>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
    </div>
    </div>

    {{--delete modal--}}

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">You want to delete this item?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Delete this item?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    {{-- <form action="{{route('admin.destroy',$user->id)}}" method="POST" class='closs-item' data -method='delete'>               @csrf
                         <button class="btn btn-primary" type="submit" >Delete</button>
                     </form>--}}
                    <a href="" class='closs-this btn btn-info' data-method='delete' data-dismis="modal">Delete</a>
                </div>
            </div>
        </div>
    </div>
@endsection